version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    restart: on-failure
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: postgres
    # container_name: postgres13
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - postgresql-user:/var/lib/postgresql/data
    ports:
      - "5442:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresql-user:
